services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_kamal_demo_development
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  app:
    build:
      context: .
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
