# Template setup of the GVC, roughly corresponding to a Heroku app.
kind: gvc
name: {{APP_NAME}}
spec:
  # For test/QA apps, ENV values are stored here in git.
  # Production apps should have values configured manually after app creation.
  env:
    - name: DATABASE_URL
      # Password does not matter because host postgres.{{APP_NAME}}.cpln.local can only be accessed
      # locally within the CPLN GVC, and postgres running on a CPLN workload is only for test apps.
      value: 'postgres://the_user:the_password@postgres.{{APP_NAME}}.cpln.local:5432/{{APP_NAME}}'
    - name: RAILS_ENV
      value: production
    - name: RAILS_SERVE_STATIC_FILES
      value: 'true'
    - name: SOLID_QUEUE_IN_PUMA
      value: 'true'
    - name: SECRET_KEY_BASE
      # For test apps, a placeholder value is fine.
      # Production apps should set this to a secure value: openssl rand -hex 64
      value: 'placeholder_secret_key_base_for_test_apps_only'
  staticPlacement:
    locationLinks:
      - {{APP_LOCATION_LINK}}

---
# Identity is needed to access secrets
kind: identity
name: {{APP_IDENTITY}}
